# Homebrew Cask for the Recall desktop app (menu-bar).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/recall - the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install --cask fredoliveira/tap/recall-desktop
#
# NOTE: the app is currently only ad-hoc signed (not Apple-notarized), so Gatekeeper
# quarantines it on first launch. Until notarization is set up, open it once via
# right-click -> Open, or clear the quarantine attribute:
#     xattr -dr com.apple.quarantine "/Applications/Recall.app"
cask "recall-desktop" do
  version "0.3.0"
  sha256 "79727b1eba3e4a9cd9af3f654e38a2ba4806b5ae977bd8aeaabf079143bb1b09"

  url "https://github.com/fredoliveira/recall/releases/download/v#{version}/Recall-universal.dmg"
  name "Recall"
  desc "Menu-bar app for the Recall MTG Arena log parser"
  homepage "https://github.com/fredoliveira/recall"

  depends_on macos: ">= :big_sur"

  app "Recall.app"

  zap trash: "~/Library/Application Support/recall"
end
