# Homebrew Cask for the 17Lands desktop app (menu-bar).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/17lands-rust — the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install --cask fredoliveira/tap/seventeenlands-desktop
#
# NOTE: the app is currently only ad-hoc signed (not Apple-notarized), so Gatekeeper
# quarantines it on first launch. Until notarization is set up, open it once via
# right-click -> Open, or clear the quarantine attribute:
#     xattr -dr com.apple.quarantine "/Applications/17Lands.app"
cask "seventeenlands-desktop" do
  version "0.1.3"
  sha256 "396a11ac3557679ca5f70788e8ba26748581a7ae2cf33af6527c02eb0caab56c"

  url "https://github.com/fredoliveira/17lands-rust/releases/download/v#{version}/17Lands-universal.dmg"
  name "17Lands"
  desc "Menu-bar app that uploads MTG Arena data to 17lands.com"
  homepage "https://github.com/fredoliveira/17lands-rust"

  depends_on macos: ">= :big_sur"

  app "17Lands.app"

  zap trash: "~/Library/Application Support/17l"
end
