# Homebrew formula for recall (binary "pour" — no Rust toolchain needed).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/recall — the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install fredoliveira/tap/recall
class Recall < Formula
  desc "Rust port of the 17Lands MTGA log client (uploads MTG Arena data to 17lands.com)"
  homepage "https://github.com/fredoliveira/recall"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/fredoliveira/recall/releases/download/v0.2.0/recall-aarch64-apple-darwin.tar.gz"
      sha256 "62b28bbd3fd28a3b62a7e72121f8c140665a8e6c144f2085301aa780a11c604c"
    end
    on_intel do
      url "https://github.com/fredoliveira/recall/releases/download/v0.2.0/recall-x86_64-apple-darwin.tar.gz"
      sha256 "f94b2da5617fbd5e95648aa1aea98bd778de36d2bbf4eb27bc62a89add34a166"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fredoliveira/recall/releases/download/v0.2.0/recall-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b7a3bec338ba074efecb7d08fd2783002dfdf45220acffbf10ef147c7ca7c866"
    end
  end

  def install
    bin.install "recall"
  end

  test do
    assert_match "17lands.com", shell_output("#{bin}/recall --help")
  end
end
