# Homebrew formula for recall (binary "pour" - no Rust toolchain needed).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/recall - the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install fredoliveira/tap/recall
class Recall < Formula
  desc "MTG Arena log parser that turns Player.log into an event stream for pluggable services"
  homepage "https://github.com/fredoliveira/recall"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fredoliveira/recall/releases/download/v0.3.0/recall-aarch64-apple-darwin.tar.gz"
      sha256 "35f5424f6a176f7fd579dc7ef072460e1cdee8f0aa14858e37e2e9bbc24b513f"
    end
    on_intel do
      url "https://github.com/fredoliveira/recall/releases/download/v0.3.0/recall-x86_64-apple-darwin.tar.gz"
      sha256 "fc36802b0b7fc089767b979c944b138c407d9fa83be4efe116c1b9246af26fa6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fredoliveira/recall/releases/download/v0.3.0/recall-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d1f4b46adc36c8b322eddf1319c1b84b4534bb7095eba037989bcc587190b3bf"
    end
  end

  def install
    bin.install "recall"
  end

  test do
    assert_match "MTG Arena log parser", shell_output("#{bin}/recall --help")
  end
end
