# Homebrew formula for seventeenlands-rust (binary "pour" — no Rust toolchain needed).
#
# GENERATED by packaging/homebrew/generate.sh in fredoliveira/17lands-rust — the release
# workflow pushes a bump here on every tagged release. Edit the generator, not this file.
#
# Users install with:
#
#     brew install fredoliveira/tap/seventeenlands-rust
class SeventeenlandsRust < Formula
  desc "Rust port of the 17Lands MTGA log client (uploads MTG Arena data to 17lands.com)"
  homepage "https://github.com/fredoliveira/17lands-rust"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/fredoliveira/17lands-rust/releases/download/v0.1.3/seventeenlands-rust-aarch64-apple-darwin.tar.gz"
      sha256 "5edee1bea5ef56f2537cd2f48d3dec0e644496dd8c4a4841c85dd702c4436a7a"
    end
    on_intel do
      url "https://github.com/fredoliveira/17lands-rust/releases/download/v0.1.3/seventeenlands-rust-x86_64-apple-darwin.tar.gz"
      sha256 "d9b343f6e8fa53dd19019ffd1483b14e383a1fa2e3d54ea2996be87e6d4fe153"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fredoliveira/17lands-rust/releases/download/v0.1.3/seventeenlands-rust-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1c500f36153b6719f15324683c6935f96d9670b88543c0f66e9260801f0f7cd6"
    end
  end

  def install
    bin.install "seventeenlands"
  end

  test do
    assert_match "17lands.com", shell_output("#{bin}/seventeenlands --help")
  end
end
